import './globals.css';
import type { Metadata } from 'next';

import { Roboto } from 'next/font/google';

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

// const oswald = Oswald({
//   subsets: ['latin'],
//   display: 'fallback',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className } className={`${poppins.variable}`}>{children}</body> */}
      {/* <body className={oswald.className}>{children}</body> */}
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
